name: Levo Kotlin Scan

on:
  workflow_dispatch:
  push:
    branches: [master, main]

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Levo Code Scanner
        uses: levoai/actions/scan@main
        with:
          authorization-key: ${{ secrets.LEVO_AUTH_KEY }}
          organization-id:   ${{ secrets.LEVO_ORG_ID }}
          app-name:          "kotlin-scan-test"
          language:          "kotlin"
          env-name:          "staging"
          saas-url:          "https://api.dev.levo.ai"
